spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  datasource:
    url: jdbc:mysql://123.206.14.25:3306/jshm?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    continue-on-error: true
    initialization-mode: always
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    show-sql: true
    database: MYSQL
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    
server:
  port: 8000
  servlet:
    session:
      timeout: 7200
        