spring:
  application:    name: userservice
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
  datasource:
    url: jdbc:mysql://localhost:3306/ws?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    continue-on-error: true
    initialization-mode: always
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    show-sql: true
    database: MYSQL
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
        
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    
server:
  port: 8000
  servlet:
    session:
      timeout: 7200
      
logging:
  level:
    root: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.spring: debug
    
eureka:  client:    serviceUrl:
#http://peer1:8201/eureka/,http://peer2:8202/eureka/
      defaultZone: http://127.0.0.1:8200/eureka/
  instance:
    prefer-ip-address: true    instance-id: ${spring.application.name}:${server.port}
    appname: UserService-HAHA
        